#!/usr/bin/env python3
r"""
Certified numerical verification for Hollow-LWE structural residuals.

This script implements the numerical certification described in Section 6.2
and Appendix D of the accompanying paper.  For each parameter row it reports:

  * the new padding-free smoothing blocklength
        n_new = ceil(k log2(q)) + 2 lambda - 1,

  * the leading-exponent explanation
        e_hat = -log2(q) * (n_new - 2k - 1),

  * a direct conservative certification from the displayed formulas for
    B_anis and B_iso:
        q^k B_anis - 1 < 2^{-(2 lambda + safety_bits)},
        q^k B_iso  - 1 < 2^{-(2 lambda + safety_bits)}.

The direct certification is not obtained by printing a tiny residual that may
round to zero.  Instead, the finite sums

        S_tau(M,R) = sum_s u_s^(tau;M,R)

are evaluated with explicit geometric tail bounds.  Ratios of such sums are
then evaluated using interval upper bounds.  Therefore the pass/fail result is
conservative: underflow or truncation cannot make B_anis or B_iso appear smaller
than the certified upper bound.

By default the script uses the bit-size log2(q) values from the Hollow-LWE
parameter table.  For an actual odd prime-power field size q, replace log2(q)
by math.log2(q) in the input CSV.
"""

from __future__ import annotations

import argparse
import csv
import math
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import mpmath as mp


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ParameterRow:
    lam: int
    log2q: float
    k: int
    h: int
    old_n: int


@dataclass(frozen=True)
class ResultRow:
    lam: int
    log2q: float
    k: int
    h: int
    old_n: int
    new_n: int
    saving: int
    reduction_pct: float
    leading_exp: float
    cert_bits: int
    passed: bool
    elapsed_sec: float


DEFAULT_PARAMS = [
    ParameterRow(128, 13, 450, 27, 7313),
    ParameterRow(128, 16, 550, 26, 11000),
    ParameterRow(192, 18, 900, 37, 20250),
    ParameterRow(256, 19, 1250, 48, 29688),
]


# ---------------------------------------------------------------------------
# Orthogonal-space helper functions
# ---------------------------------------------------------------------------

def w_tau(tau: str, M: int) -> int:
    """Witt index of a non-degenerate space of type tau and dimension M."""
    if tau == "P":
        return (M - 1) // 2
    if tau == "H":
        return M // 2
    if tau == "E":
        return M // 2 - 1
    raise ValueError(f"unknown type tau={tau!r}; expected 'P', 'H', or 'E'")


def new_blocklength(lam: int, log2q: float, k: int) -> int:
    """Compute n_new = ceil(k log2(q)) + 2 lambda - 1."""
    return math.ceil(k * log2q) + 2 * lam - 1


def qneg(log2q: float, a: int) -> mp.mpf:
    """Return q^{-a} as 2^{-log2(q)*a}."""
    return mp.power(2, -mp.mpf(log2q) * a)


def qpow(log2q: float, a: int) -> mp.mpf:
    """Return q^a as 2^{log2(q)*a}; a may be negative."""
    return mp.power(2, mp.mpf(log2q) * a)


def recurrence_ratio_abs_bound(log2q: float) -> mp.mpf:
    r"""Uniform upper bound for |u_{s+1}/u_s|.

    After factoring every term q^a +- 1 as q^a(1 +- q^{-a}), the recurrence
    ratio has the form

        |u_{s+1}/u_s| = q^{-1} * correction_s.

    In the parameter ranges used here, all numerator factors are at most 1
    except a single factor bounded by 1+q^{-1}; each denominator factor is at
    least 1-q^{-1}.  Thus the conservative bound

        rho_q = q^{-1}(1+q^{-1})/(1-q^{-1})^3

    controls the remaining tail by a geometric series.
    """
    qinv = qneg(log2q, 1)
    return qinv * (1 + qinv) / (1 - qinv) ** 3


# ---------------------------------------------------------------------------
# Certified finite sums S_tau(M,R)
# ---------------------------------------------------------------------------

def sum_u_interval(
    log2q: float,
    tau: str,
    M: int,
    R: int,
    tail_bits: int,
    label: str = "",
    quiet: bool = False,
) -> tuple[mp.mpf, mp.mpf]:
    r"""Compute an interval enclosure for S_tau(M,R).

    Returns (S_mid, err) such that

        S_tau(M,R) in [S_mid - err, S_mid + err].

    The terms are generated by the stable recurrence

        u_{s+1}/u_s = -q^{-1} * product(1 +- q^{-a}).

    Once the remaining geometric tail is below 2^{-tail_bits}, the loop stops.
    This is the step that avoids relying on round-to-zero effects.
    """
    W = w_tau(tau, M)
    limit = min(R, W)
    rho = recurrence_ratio_abs_bound(log2q)
    target = mp.power(2, -tail_bits)

    u = mp.mpf(1)
    S = mp.mpf(1)

    if label and not quiet:
        print(f"    {label}: tau={tau}, M={M}, R={R}, max_terms={limit}")

    for s in range(limit):
        A = M - W - s - 1
        B = W - s
        C = R - s
        D = M - R - s
        E = M - 2 * s
        F = M - 2 * s - 1

        ratio = (
            -qneg(log2q, 1)
            * (1 + qneg(log2q, A))
            * (1 - qneg(log2q, B))
            / (1 - qneg(log2q, s + 1))
            * (1 - qneg(log2q, C))
            * (1 - qneg(log2q, D))
            / ((1 - qneg(log2q, E)) * (1 - qneg(log2q, F)))
        )

        u *= ratio
        S += u

        # Tail after the current term:
        #   |u_{s+1}| + |u_{s+2}| + ... <= |u_s| rho/(1-rho).
        tail = abs(u) * rho / (1 - rho)
        if tail < target:
            if label and not quiet:
                print(f"      stop after {s + 1} terms; tail < 2^-{tail_bits}")
            return S, tail

    if label and not quiet:
        print(f"      completed all {limit} terms")
    return S, mp.mpf(0)


def ratio_upper(num: mp.mpf, num_err: mp.mpf, den: mp.mpf, den_err: mp.mpf) -> mp.mpf:
    """Conservative upper bound for num/den from interval enclosures."""
    den_lower = den - den_err
    if den_lower <= 0:
        raise RuntimeError("denominator interval contains zero; increase precision")
    return (num + num_err) / den_lower


# ---------------------------------------------------------------------------
# Upper bounds for q^k B_anis and q^k B_iso
# ---------------------------------------------------------------------------

def qk_anis_branch_upper(
    log2q: float,
    m0: int,
    h: int,
    m: int,
    r: int,
    S_num: mp.mpf,
    E_num: mp.mpf,
    S_den: mp.mpf,
    E_den: mp.mpf,
) -> mp.mpf:
    r"""Upper bound for one branch of q^k B_anis.

    We compute q^k B directly after cancelling leading q-powers.  This avoids
    huge intermediate values and leaves only factors of the form 1 +- q^{-a}.
    """
    factor_Y = (1 + qneg(log2q, m0 - h)) / (1 + qneg(log2q, m0))
    factor_G = (1 - qneg(log2q, m - r)) / (1 - qneg(log2q, m))
    return factor_Y * factor_G * ratio_upper(S_num, E_num, S_den, E_den)


def qk_biso_upper(
    log2q: float,
    n: int,
    k: int,
    h: int,
    m: int,
    r: int,
    w: int,
    S_m2: mp.mpf,
    E_m2: mp.mpf,
    S_m: mp.mpf,
    E_m: mp.mpf,
) -> mp.mpf:
    """Conservative upper bound for q^k B_iso from the Section 6.2 formula."""
    # Event E1 contribution after multiplying by q^k.
    exp1 = k + h - w - (n - w - 1)
    T1 = (
        qpow(log2q, exp1)
        * (1 - qneg(log2q, h))
        / ((1 - qneg(log2q, w)) * (1 + qneg(log2q, n - w - 1)))
    )

    # Event E2 contribution.  Normalize by the leading q^{n-h-1} term so that
    # only small correction factors remain.
    a1 = w - (n - h - 1)
    a2 = (n - w - 1) - (n - h - 1)
    a3 = h - (n - h - 1)
    bracket = mp.mpf(1) + qpow(log2q, a1) - qpow(log2q, a2) - qpow(log2q, a3)
    P2_norm = bracket / ((1 - qneg(log2q, w)) * (1 + qneg(log2q, n - w - 1)))

    grass = (
        (1 - qneg(log2q, m - r))
        * (1 - qneg(log2q, m - r - 1))
        / ((1 - qneg(log2q, m)) * (1 - qneg(log2q, m - 1)))
    )

    return T1 + P2_norm * grass * ratio_upper(S_m2, E_m2, S_m, E_m)


# ---------------------------------------------------------------------------
# Row-level certification
# ---------------------------------------------------------------------------

def certify_row(
    row: ParameterRow,
    safety_bits: int,
    tail_margin: int,
    guard_bits: int,
    quiet: bool = False,
) -> ResultRow:
    """Compute one table row and certify the structural residual."""
    lam, log2q, k, h, old_n = row.lam, row.log2q, row.k, row.h, row.old_n
    n = new_blocklength(lam, log2q, k)
    m = n - 2 * h
    r = k - h
    m0 = n // 2

    verify_bits = 2 * lam + safety_bits
    tail_bits = verify_bits + tail_margin
    mp.mp.prec = verify_bits + tail_margin + guard_bits

    start = time.time()
    if not quiet:
        print("=" * 78)
        print(f"lambda={lam}, log2q={log2q}, k={k}, h={h}, old_n={old_n}, new_n={n}")
        print(f"verify q^k B - 1 < 2^-{verify_bits}; precision={mp.mp.prec} bits")

    # The default table rows have odd n_new, so tau_n=P.  The even branch is
    # kept for completeness; for q equiv 1 mod 4 the even-dimensional ambient
    # type is H.  If a different concrete odd q is used, adjust this branch.
    if n % 2 == 1:
        tau_n = "P"
        w = (n - 1) // 2
        S_P_m, E_P_m = sum_u_interval(log2q, "P", m, r, tail_bits, "S_P(m,r)", quiet)
        S_H_m1, E_H_m1 = sum_u_interval(log2q, "H", m - 1, r, tail_bits, "S_H(m-1,r)", quiet)
        S_E_m1, E_E_m1 = sum_u_interval(log2q, "E", m - 1, r, tail_bits, "S_E(m-1,r)", quiet)
        qk_Banis = max(
            qk_anis_branch_upper(log2q, m0, h, m, r, S_H_m1, E_H_m1, S_P_m, E_P_m),
            qk_anis_branch_upper(log2q, m0, h, m, r, S_E_m1, E_E_m1, S_P_m, E_P_m),
        )
        S_tau_m, E_tau_m = S_P_m, E_P_m
        S_tau_m2, E_tau_m2 = sum_u_interval(log2q, "P", m - 2, r, tail_bits, "S_P(m-2,r)", quiet)
    else:
        tau_n = "H"
        w = n // 2
        S_P_m1, E_P_m1 = sum_u_interval(log2q, "P", m - 1, r, tail_bits, "S_P(m-1,r)", quiet)
        S_H_m, E_H_m = sum_u_interval(log2q, "H", m, r, tail_bits, "S_H(m,r)", quiet)
        S_E_m, E_E_m = sum_u_interval(log2q, "E", m, r, tail_bits, "S_E(m,r)", quiet)
        qk_Banis = max(
            qk_anis_branch_upper(log2q, m0, h, m, r, S_P_m1, E_P_m1, S_H_m, E_H_m),
            qk_anis_branch_upper(log2q, m0, h, m, r, S_P_m1, E_P_m1, S_E_m, E_E_m),
        )
        S_tau_m, E_tau_m = S_H_m, E_H_m
        S_tau_m2, E_tau_m2 = sum_u_interval(log2q, "H", m - 2, r, tail_bits, "S_H(m-2,r)", quiet)

    qk_Biso = qk_biso_upper(log2q, n, k, h, m, r, w, S_tau_m2, E_tau_m2, S_tau_m, E_tau_m)

    threshold = mp.power(2, -verify_bits)
    dev_anis = qk_Banis - 1
    dev_iso = qk_Biso - 1
    passed = (dev_anis < threshold) and (dev_iso < threshold)

    leading_exp = -log2q * (n - 2 * k - 1)
    saving = old_n - n
    reduction_pct = 100.0 * saving / old_n
    elapsed = time.time() - start

    if not quiet:
        print(f"q^k B_anis - 1 upper: {mp.nstr(dev_anis, 8)}")
        print(f"q^k B_iso  - 1 upper: {mp.nstr(dev_iso, 8)}")
        print(f"leading exponent: {leading_exp}")
        print(f"direct certification: < 2^-{verify_bits}, pass={passed}")
        print(f"elapsed: {elapsed:.2f}s")

    return ResultRow(lam, log2q, k, h, old_n, n, saving, reduction_pct, leading_exp, verify_bits, passed, elapsed)


# ---------------------------------------------------------------------------
# Input/output helpers
# ---------------------------------------------------------------------------

def load_params(path: Path) -> list[ParameterRow]:
    """Load parameter rows from CSV with columns lambda,log2q,k,h,old_n."""
    rows: list[ParameterRow] = []
    with path.open(newline="") as f:
        reader = csv.DictReader(f)
        for item in reader:
            rows.append(
                ParameterRow(
                    lam=int(item["lambda"]),
                    log2q=float(item["log2q"]),
                    k=int(item["k"]),
                    h=int(item["h"]),
                    old_n=int(item["old_n"]),
                )
            )
    return rows


def print_summary(rows: Iterable[ResultRow]) -> None:
    """Print a compact table matching the paper."""
    print("=" * 78)
    print("lambda log2q k h old_n new_n saving reduction leading_exp cert pass")
    for row in rows:
        print(
            f"{row.lam:3d} {row.log2q:5.0f} {row.k:4d} {row.h:3d} "
            f"{row.old_n:6d} {row.new_n:6d} {row.saving:6d} "
            f"{row.reduction_pct:6.2f}% {row.leading_exp:10.0f} "
            f"<-{row.cert_bits:<4d} {row.passed}"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description="Certify Hollow-LWE structural residuals.")
    parser.add_argument("--params", type=Path, default=None,
                        help="CSV file with columns lambda,log2q,k,h,old_n")
    parser.add_argument("--safety-bits", type=int, default=64,
                        help="certify below 2^{-(2 lambda + safety_bits)}")
    parser.add_argument("--tail-margin", type=int, default=128,
                        help="extra tail precision for each truncated S_tau sum")
    parser.add_argument("--guard-bits", type=int, default=256,
                        help="extra mpmath precision bits")
    parser.add_argument("--quiet", action="store_true", help="suppress per-row progress output")
    args = parser.parse_args()

    params = load_params(args.params) if args.params else DEFAULT_PARAMS
    results = [
        certify_row(row, args.safety_bits, args.tail_margin, args.guard_bits, args.quiet)
        for row in params
    ]
    print_summary(results)


if __name__ == "__main__":
    main()
